# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='temp',
        ),
    ]
